calibration_methods/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from calibration import views
from . import settings

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('add_config/', views.Add_config.as_view(), name='add_config'),
    path('edit_config/<int:config_id>', views.Add_config.as_view(), name='edit_config'),
    path('running/<int:config_id>', views.Running.as_view(), name='running'),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

calibration/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib import admin

CAM_TYPES = [
    ('omni', 'Omnidirectional'),
    ('perspective', 'Perspective'),
    ('pinhole', 'Pinhole'),
    ('fisheye', 'Fisheye')
]

VIS_TYPES = [
    ('mi-r', 'show points within a range, colored by reflectivity'),
    ('mi', 'show points within a range'),
    ('edge-e', 'show edge points on image of edges'),
    ('edge', 'show edge points')
]

INI_TYPES = [
    ('quaternion', 'quaternion'),
    ('euler', 'euler')
]

class Camera(models.Model):
    cname = models.CharField(max_length=100)
    ctype = models.CharField(max_length=15, choices=CAM_TYPES)
    height, width = models.IntegerField(), models.IntegerField()
    ck1, ck2, cp1, cp2, ck3 = models.FloatField(blank=True, null=True), \
                              models.FloatField(blank=True, null=True), \
                              models.FloatField(blank=True, null=True), \
                              models.FloatField(blank=True, null=True), \
                              models.FloatField(blank=True, null=True)
    cfx, cfy, cx, cy, cb1 = models.FloatField(blank=True, null=True),\
                            models.FloatField(blank=True, null=True), \
                            models.FloatField(blank=True, null=True), \
                            models.FloatField(blank=True, null=True), \
                            models.FloatField(blank=True, null=True)
    mask = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.cname + '-' + self.ctype

class Lidar(models.Model):
    lname = models.CharField(max_length=100)
    laser_num = models.IntegerField(default=0)

    def __str__(self):
        return self.lname

class Config(models.Model):

    name = models.CharField(max_length=100)
    # frame setting
    select_frame_by_hand = models.BooleanField(default=False)
    selected = models.CharField(max_length=100, blank=True, null=True)

    start_frame, end_frame = models.IntegerField(blank=True, null=True), models.IntegerField(blank=True, null=True)
    use_frame = models.IntegerField(blank=True, null=True)

    scan_path, img_path = models.CharField(max_length=200), models.CharField(max_length=200)
    img_type = models.CharField(max_length=20)
    skip_line = models.IntegerField(default=0)
    rxyz = models.BooleanField(default=False)
    delimiter = models.CharField(max_length=10)

    # output setting
    verbose = models.BooleanField(default=False)
    vis = models.CharField(max_length=20, choices=VIS_TYPES)

    # test
    test_amount = models.IntegerField(default=0)
    R_range = models.FloatField(blank=True, null=True)
    t_range = models.FloatField(blank=True, null=True)


    # camera & lidar
    camera = models.ForeignKey(Camera, on_delete=models.CASCADE)
    lidar = models.ForeignKey(Lidar, on_delete=models.CASCADE)

    # method mi
    mi_use = models.BooleanField(default=False)
    show_distribution = models.BooleanField(default=False)

    # method edge
    edge_use = models.BooleanField(default=False)
    check_laser = models.BooleanField(default=False)
    edge_path = models.CharField(max_length=200, blank=True, null=True)
    discontinuity = models.FloatField(blank=True, null=True)

    # initial guess
    ini_type = models.CharField(max_length=10, choices=INI_TYPES)
    degree = models.BooleanField(blank=True, null=True, default=False)
    R1, R2, R3, R4 = models.FloatField(default=0), models.FloatField(default=0), models.FloatField(default=0), \
                     models.FloatField(default=0, blank=True, null=True)
    t1, t2, t3 = models.FloatField(default=0), models.FloatField(default=0), models.FloatField(default=0)

class ConfigForm(ModelForm):
    class Meta:
        model = Config
        fields = '__all__'
    def __init__(self, *args, **kwargs):
        super(ConfigForm, self).__init__(*args, **kwargs)
        for field in self.fields.keys():
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })


class CameraForm(ModelForm):
    class Meta:
        model = Camera
        fields = '__all__'

    # def __init__(self, *args, **kwargs):
    #     super(CameraForm, self).__init__(*args, **kwargs)
    #     for field in self.fields.keys():
    #         self.fields[field].widget.attrs.update({
    #             'class':'form-control'
    #         })
    #


class LidarForm(ModelForm):
    class Meta:
        model = Lidar
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(LidarForm, self).__init__(*args, **kwargs)
        for field in self.fields.keys():
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

calibration/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View, generic
from calibration.models import ConfigForm, CameraForm, LidarForm, Camera as Cam, Lidar, Config
import json
import numpy as np
import sys
from django.urls import reverse

from calibration.models import Config, Camera as Cam, Lidar

class Running(View):
    template = 'running.html'

    def get(self, request, config_id):
        return render(request, self.template, {
            'config_id': config_id
        })

class Index(View):
    template = 'index.html'
    def get(self, request):
        return render(request, self.template, {'configs': Config.objects.all()})


class Add_config(View):
    template = 'add_config.html'
    json_config_keys = {
        'camera': {
            'all': {'type':'ctype', 'height': 'height', 'width': 'width', 'mask': 'mask'},
            'perspective': ['k', 'dist'],
            'omni': [],
            'fisheye': ['f', 'cx', 'cy', 'k1', 'k2', 'k3', 'b1'],
            'pinhole': ['f', 'cx', 'cy', 'sx', 'sy']
        }
    }

    def return_os(self):
        if sys.platform=='darwin':
            return 'mac'
        if sys.platform == 'win32' or sys.platform=='cygwin':
            return 'win'
        if sys.platform == 'linux':
            return 'linux'
        return ''

    def get(self, request, config_id=None):
        if(config_id):
            config = get_object_or_404(Config, pk=config_id)
            cam = config.camera
            lidar = config.lidar
        else:
            config = Config()
            cam = Cam()
            lidar = Lidar()
        return render(request, self.template,
                      {
                          'camera': cam,
                          'lidar': lidar,
                          'config': config,
                      })

    def post(self, request, config_id=None):
        if 'file' in request.FILES:
            data = request.FILES['file'].read()
            j = json.loads(data)
            models, msgs = self.load_from_json(j)
            models['config'].name = str(request.FILES['file']).replace('.json', '')

            return render(request, self.template,
                          {
                              'msgs': msgs,
                              'camera': models['cam'],
                              'lidar': models['lidar'],
                              'config': models['config']
                          })
        else:

            data = request.POST.copy()

            if config_id:
                config = get_object_or_404(Config, pk=config_id)
                cam = get_object_or_404(Cam, pk=config.camera_id)
                lid = get_object_or_404(Lidar, pk=config.lidar_id)
                new_cam_form = CameraForm(data, instance=cam)
                new_lidar_form = LidarForm(data, instance=lid)
            else:
                new_cam_form = CameraForm(data)
                new_lidar_form = LidarForm(data)
            if new_cam_form.is_valid() and new_lidar_form.is_valid():
                new_cam = new_cam_form.save()
                new_lidar = new_lidar_form.save()
            else:
                return HttpResponse('invalid camera or lidar')
            data.update({'camera': new_cam.pk})
            data.update({'lidar': new_lidar.pk})
            if 'test' not in data:
                data.update({'test_amount': 0})
            if config_id:
                new_config_form = ConfigForm(data, instance=config)
            else:
                new_config_form = ConfigForm(data)
            if new_config_form.is_valid():
                new_config = new_config_form.save()
            else:
                return HttpResponse(new_config_form.as_table())
            return HttpResponseRedirect(reverse('running', args=(new_config.pk,)))

    def load_from_json(self, data):
        cam = Cam()
        lidar = Lidar()
        config = Config()
        msgs = []
        # load camera
        if 'camera' in data:
            c_setting = data['camera']
            not_found = []
            try:
                cam.cname = c_setting['name']
            except:
                not_found.append('name')
            try:
                cam.width = c_setting['width']
            except:
                not_found.append('width')
            try:
                cam.height = c_setting['height']
            except:
                not_found.append('height')
            try:
                cam.mask = c_setting['mask_' + self.return_os()]
            except:
                not_found.append('mask')
            try:
                cam.ctype = c_setting['type']
                if cam.ctype == 'perspective':
                    try:
                        cam.cfx = c_setting['k'][0][0]
                        cam.cfy = c_setting['k'][1][1]
                        cam.cx = c_setting['k'][0][2]
                        cam.cy = c_setting['k'][1][2]
                    except:
                        not_found += ['f', 'center of camera']
                    try:
                        # in case the dist is not in ideal shape
                        dist = np.zeros((5, ))
                        din = np.array(c_setting['dist']).reshape((-1, ))
                        i = 5 if din.shape[0] > 5 else din.shape[0]
                        dist[:i] = din
                        cam.ck1 = dist[0]
                        cam.ck2 = dist[1]
                        cam.cp1 = dist[2]
                        cam.cp2 = dist[3]
                        cam.ck3 = dist[4]
                    except:
                        not_found += ['distortion coefficient']
                if cam.ctype == 'fisheye' or cam.ctype == 'pinhole':
                    try:
                        cam.cx = c_setting['cx']
                    except:
                        not_found.append('cx')
                    try:
                        cam.cy = c_setting['cy']
                    except:
                        not_found.append('cy')
                    try:
                        cam.cfx, cam.cfy = c_setting['f'], c_setting['f']
                    except:
                        not_found.append('f')

                    if cam.ctype == 'pinhole':
                        try:
                            cam.fx *= c_setting['sx']
                        except:
                            pass
                        try:
                            cam.fy *= c_setting['sy']
                        except:
                            pass

                    if cam.ctype == 'fisheye':
                        try:
                            cam.ck1 = c_setting['k1']
                        except:
                            not_found.append('k1')
                        try:
                            cam.ck2 = c_setting['k2']
                        except:
                            not_found.append('k2')
                        try:
                            cam.cb1 = c_setting['b1']
                        except:
                            not_found.append('b1')
                        try:
                            cam.ck3 = c_setting['k3']
                        except:
                            not_found.append('k3')
            except:
                not_found.append('type')
            msgs += ['' if len(not_found) == 0 else f"camera: {', '.join(not_found)}"]
        else:
            msgs += ["camera information"]
        # load lidar
        try:
            lidar.laser_num = data['frame']['laser_num']
            msgs += ['LiDAR: name']
        except:
            msgs += ['LiDAR: name, laser_num']

        method_not_found = {
            'frames': [],
            'methods': [],
            'initial guess': [],
            'output setting': [],
            'running setting': []
        }
        try:
            config.select_frame_by_hand = data['select_frame_by_hand']
            if data['select_frame_by_hand']:
                try:
                    config.selected = str(", ".join(data['selected']))
                except:
                    method_not_found['frames'].append('selected')
            else:
                try:
                    config.start_frame = data['start_frame']
                except:
                    method_not_found['frames'].append('start_frame')
                try:
                    config.end_frame = data['end_frame']
                except:
                    method_not_found['frames'].append('end_frame')
                try:
                    config.use_frame = data['use']
                except:
                    method_not_found['frames'].append('use')
        except:
            method_not_found['frames'].append('select_frame_by_hand')
        if 'method' in data:
            method = data['method']
            try:
                config.verbose = method['verbose']
            except:
                method_not_found['output setting'].append('verbose')
            try:
                config.vis = method['vis']
            except:
                method_not_found['output setting'].append('vis')
            if 'test' in method:
                try:
                    config.test_amount = method['test']['amount']
                    if config.test_amount > 0:
                        try:
                            config.R_range = abs(method['R_range'][0])
                        except:
                            method_not_found['running setting'].append("R_range")
                        try:
                            config.t_range = abs(method['t_range'][0])
                        except:
                            method_not_found['running setting'].append("t_range")
                except:
                    method_not_found['running setting'].append('all')
            else:
                method_not_found['running setting'].append('all')
            if 'edge' in method:
                try:

calibration/templates/config_form/cams/fisheye.html
<div id="fisheye">
<div class="row">
    <div class="col-md-6">
        <label for="id_cfx">Focal length</label>
    </div>
    <div class="col-md-6">
        <label for="id_cx">Center of camera</label>
    </div>

</div>
<div class="form-row">
    <div class="col-md-3 mb-3">
        <input type="number" class="form-control" id="id_cfx" name="cfx"
               placeholder="fx" value="{{ camera.cfx | default_if_none:'' }}" required>
    </div>
    <div class="col-md-3 mb-3">
        <div class="w-100"></div>
        <input type="number" class="form-control" id="id_cfy" name="cfy" aria-label="fy"
               placeholder="fy" value="{{ camera.cfy | default_if_none:'' }}" required>
    </div>
    <div class="col-md-3 mb-3">
        <input type="number" class="form-control" id="id_cx" name="cx"
               placeholder="cx" value="{{ camera.cx | default_if_none:'' }}" required>
    </div>
    <div class="col-md-3 mb-3">
        <input type="number" class="form-control" id="id_cy" name="cy" aria-label="cy"
               placeholder="cy" value="{{ camera.cy | default_if_none:'' }}" required>
    </div>
</div>
<div class="row col-md-4">
    <label for="id_ck1">Distortion factors</label>
</div>
<div class="form-row">
    <div class="col-md-3 mb-3">

        <input type="number" class="form-control" id="id_ck1" name="ck1"
               placeholder="k1" value="{{ camera.ck1 | default_if_none:'' }}" required>
    </div>
    <div class="col-md-3 mb-3">
        <input type="number" class="form-control" id="id_ck2" name="ck2" aria-label="k2"
               placeholder="k2" value="{{ camera.ck2 | default_if_none:'' }}" required>
    </div>
    <div class="col-md-3 mb-3">
        <input type="number" class="form-control" id="id_ck3" name="ck3" aria-label="k3"
               placeholder="k3" value="{{ camera.ck3 | default_if_none:'' }}" required>
    </div>
    <div class="col-md-3 mb-3">
        <input type="number" class="form-control" id="id_cb1" name="cb1" aria-label="b1"
               placeholder="b1" value="{{ camera.cb1 | default_if_none:'' }}" required>
    </div>
</div>
</div>

calibration/templates/config_form/cams/omni.html
<div id="omni" ></div>

calibration/templates/config_form/cams/perspective.html
<div id="perspective">
<div class="row">
    <div class="col-md-6">
        <label for="id_cfx">Focal length</label>
    </div>
    <div class="col-md-6">
        <label for="id_cx">Center of camera</label>
    </div>
</div>
<div class="form-row">
    <div class="col-md-3 mb-3">
        <input type="number" class="form-control" id="id_cfx" name="cfx"
               placeholder="fx" value="{{ camera.cfx | default_if_none:'' }}" required>
    </div>
    <div class="col-md-3 mb-3">
        <div class="w-100"></div>
        <input type="number" class="form-control" id="id_cfy" name="cfy" aria-label="fy"
               placeholder="fy" value="{{ camera.cfy | default_if_none:'' }}" required>
    </div>
    <div class="col-md-3 mb-3">
        <input type="number" class="form-control" id="id_cx" name="cx"
               placeholder="cx" value="{{ camera.cx | default_if_none:'' }}" required>
    </div>
    <div class="col-md-3 mb-3">
        <input type="number" class="form-control" id="id_cy" name="cy" aria-label="cy"
               placeholder="cy" value="{{ camera.cy | default_if_none:'' }}" required>
    </div>
</div>
    <div class="row col-md-4">
        <label for="id_ck1">Distortion factors</label>
    </div>
    <div class="form-row">
        <div class="col-md-3 mb-3">

            <input type="number" class="form-control" id="id_ck1" name="ck1"
                   placeholder="k1" value="{{ camera.ck1 | default_if_none:'' }}" required>
        </div>
        <div class="col-md-3 mb-3">
            <input type="number" class="form-control" id="id_ck2" name="ck2" aria-label="k2"
                   placeholder="k2" value="{{ camera.ck2 | default_if_none:'' }}" required>
        </div>
        <div class="col-md-2 mb-3">
            <input type="number" class="form-control" id="id_cp1" name="cp1" aria-label="p1"
                   placeholder="p1" value="{{ camera.cp1 | default_if_none:'' }}" required>
        </div>
        <div class="col-md-2 mb-3">
            <input type="number" class="form-control" id="id_cp2" name="cp2" aria-label="p2"
                   placeholder="p2" value="{{ camera.cp2 | default_if_none:'' }}" required>
        </div>
        <div class="col-md-2 mb-3">
            <input type="number" class="form-control" id="id_ck3" name="ck3" aria-label="k3"
                   placeholder="k3" value="{{ camera.ck3 | default_if_none:'' }}" required>
        </div>
    </div>
</div>

calibration/templates/config_form/cams/pinhole.html
<div id="pinhole">
    <div class="row">
        <div class="col-md-6">
            <label for="id_cfx">Focal length</label>
        </div>
        <div class="col-md-6">
            <label for="id_cx">Center of camera</label>
        </div>

    </div>
    <div class="form-row">
        <div class="col-md-3 mb-3">
            <input type="number" class="form-control" id="id_cfx" name="cfx"
                   placeholder="fx" value="{{ camera.cfx | default_if_none:'' }}" required>
        </div>
        <div class="col-md-3 mb-3">
            <div class="w-100"></div>
            <input type="number" class="form-control" id="id_cfy" name="cfy" aria-label="fy"
                   placeholder="fy" value="{{ camera.cfy | default_if_none:'' }}" required>
        </div>
        <div class="col-md-3 mb-3">
            <input type="number" class="form-control" id="id_cx" name="cx"
                   placeholder="cx" value="{{ camera.cx | default_if_none:'' }}" required>
        </div>
        <div class="col-md-3 mb-3">
            <input type="number" class="form-control" id="id_cy" name="cy" aria-label="cy"
                   placeholder="cy" value="{{ camera.cy | default_if_none:'' }}" required>
        </div>
    </div>
</div>